### ISSUE TITLE
Gas Optimization Proposal (30%-50%)

### ISSUE THREAD

**Issue by codeislight1** [HorizenLabs/ape-staking-public#2]
I've noticed that there is room for optimizing the staking contract, so I wrote a more optimized version, here are the stats for 2 test cases for gas cost reduction stats:
first one had used 1 NFT for deposit / claim / withdraw and tested through 1, 2, 3 and 5 iterative calls for forementioned functions:

![1](https://user-images.githubusercontent.com/104497451/201688210-54be6962-4005-4ef9-9073-8f0aa3ee3aa8.jpg)

second one had used 2 NFTs for deposit / claim / withdraw and used 1, 2, 3 and 5 iterative calls for forementioned functions:

![2](https://user-images.githubusercontent.com/104497451/201688222-b875c6e8-89de-4982-b428-7739a96b8999.jpg)

if it's worth having a look at it, let me know if I should make a pull request, thank you.

**Comment by loucaponi** [comment]
Hey @codeislight1 thanks for reaching out.  Would you mind making a PR to this repo?  We would need to see the desired changes in more detail in order to assess the scope.

**Comment by codeislight1** [comment]
Hi @loucaponi , i have made a repo that has all the changes made and with comments on each change, with a script to generate the gas difference.
https://github.com/codeislight1/optimized-apecoin-staking

**Comment by codeislight1** [comment]
any feedback?

**Comment by apecollector** [comment]
@codeislight1 why don't you make a pull request with the changes to the contract itself? That would be much easier to assess the differences.

**Comment by codeislight1** [comment]
i have posted the link to the repo which includes the gas difference script which makes it easier to calculate, sure i ll PR the changes made :)

**Comment by codeislight1** [comment]
i have opened a PR with each commit containing separate optimization, let me know if there is anything else needed from my end.

**Comment by loucaponi** [comment]
@codeislight1 your requested changes are being looked at by our team as we make final decisions around contract changes. Your thorough explanations around each suggestion are greatly appreciated. Very nice work 👍🏼

**Comment by codeislight1** [comment]
thank you very much, i am glad to hear that

**Comment by codeislight1** [comment]
@loucaponi , can you send me a dm on twitter, ty
https://twitter.com/codeislight

**Comment by loucaponi** [comment]
Hey @codeislight1 following up on this issue.  We incorporated many of your submissions into our latest contract update, which will be on testnet soon.  Thanks again for the thoughtful and rigorous effort on your end.

**Comment by codeislight1** [comment]
My pleasure, thank you for the update, I can't wait to see it on the testnet :)
