### ISSUE TITLE
No tests or audits?

### ISSUE THREAD

**Issue by apecollector** [HorizenLabs/ape-staking-public#4]
Has there been any audits done from independent organizations like Halborn or CertiK? These audits [were done on the ApeCoin contract](https://github.com/HorizenLabs/grapes-erc20-public#audit) which found several issues that were remedied. 

Also I find it odd that this repo is missing any tests, the only script is for deploying and setting up staking but there's seemingly no code for actually staking and verifying the correct inputs and outputs.

**Comment by Cache-and-Burn** [comment]
@apecollector Halborn did an audit in September 

https://drive.google.com/file/d/1ppauv4me-WWWKIwWUUiWP32vtisXcKKg/view

**Comment by montanaflynn** [comment]
Thanks

**Comment by montanaflynn** [comment]
@rdoria1 @devopsbo3 @loucaponi was there a new audit for the bug bounty and gas optimization changes?

**Comment by loucaponi** [comment]
Hello @montanaflynn, there was a new audit (conducted by Halborn Security), located on the homepage of the docs: https://docs.apestake.io/#/

Regarding tests, etc, they do not exist on this public repository.  This repo is mainly for the purposes of the bug bounty, allowing devs to get up and running quickly on their local machines.
